# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    version=$(node -p "require('./package.json').version") 
    echo "##vso[build.updatebuildnumber]$version"
  displayName: 'Configure build number from NPM package.json'

- powershell: |
    Write-Host "Configuring environment to run tests"
    $version = (Get-Package -Name 'Pester').Version
    if ($version -ne '4.10.0') {
        Write-Host "##[warning]Detected incompatible Pester version ($version)."
        if ($version) {
            Get-Package -Name Pester | Uninstall-Package -Scope CurrentUser
        }
        Install-Package -Name Pester -MaximumVersion '4.10.0' -Scope CurrentUser
    }
    else {
        Write-Host "Pester is installed according to the requirements."
    }
  displayName: 'Configure test environment'
  errorActionPreference: stop
  
